### ISSUE TITLE
Crash when going to Manage ->Tags Moderation

### ISSUE THREAD

**Issue by vaspervnp** [DemocracyOS/democracyos#1533] opened 2018-03-08 17:38 UTC
I have installed and run a service on https://democracy.sonsofpiracy.org. 
However, when I go to Manage ->Tags Moderation the service crashes and must be restarted to continue work.

**Comment by franciclo** [comment] 2018-03-08 18:45
Hi, can you show see any logs related to the crash?
Also i change the title of the issue because we are using [v3] prefix for version 3 issues only

**Comment by franciclo** [comment] 2018-03-08 19:08
I was able to reproduce it and now working in a solution.
Thank you for reporting it!

**Comment by franciclo** [comment] 2018-03-08 19:19
fixed on 2.10.2

**Closed by franciclo** 2018-03-08 19:19 UTC

**Comment by vaspervnp** [comment] 2018-03-09 12:01
Excellent. Thank you.
